name: Pipeline to Push Docker Images with Branch and Label Conditions

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          token_format: access_token
          workload_identity_provider: ${{ secrets.WIP }}
          service_account: ${{ secrets.SERVICE_ACCOUNT }}
          access_token_lifetime: 300s
          project_id: "virtual-voyage-423511-d7"

      - name: Docker Build (dev)
        if: contains(github.event.pull_request.labels.*.name, 'dev')
        run: |
          docker build -t "us-central1-docker.pkg.dev/virtual-voyage-423511-d7/dev" .

      - name: Docker Push (dev image on pull request with dev label)
        if: contains(github.event.pull_request.labels.*.name, 'dev')
        run: |
          docker push "us-central1-docker.pkg.dev/virtual-voyage-423511-d7/dev"

      - name: Docker Build (prod)
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          docker build -t "us-central1-docker.pkg.dev/virtual-voyage-423511-d7/prod" .

      - name: Docker Push (prod image on merge to main)
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          docker push "us-central1-docker.pkg.dev/virtual-voyage-423511-d7/prod"